services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    image: ghcr.io/chiballc/manyumba
    labels:
      - com.centurylinklabs.watchtower.enable="true"

  db:
    extends:
      file: docker-compose.base.yml
      service: db

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --label-enable

volumes:
  postgres_data:
