services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    build:
      context: .
      dockerfile: Dockerfile

  db:
    extends:
      file: docker-compose.base.yml
      service: db
      
volumes:
  postgres_data: